spring.application.name=tech-taste
spring.datasource.url=jdbc:postgresql://localhost:5432/tech-taste-db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true